#!/bin/bash
# Watchtower 로그 확인 스크립트

echo "🔍 Watchtower 로그 확인 명령어"
echo "================================"
echo ""
echo "운영 서버에서 실행:"
echo ""
echo "# 1. Watchtower 컨테이너 확인"
echo "docker ps | grep watchtower"
echo ""
echo "# 2. 최근 100줄 로그"
echo "docker logs watchtower --tail 100"
echo ""
echo "# 3. 실시간 로그 모니터링"
echo "docker logs -f watchtower"
echo ""
echo "# 4. 특정 이미지 관련 로그만 필터"
echo "docker logs watchtower --tail 200 | grep -E '(blacklist|192.168.50.215:1234|registry.jclee.me|Unable to find|Checking|Updated)'"
echo ""
echo "# 5. 에러 로그만 확인"
echo "docker logs watchtower --tail 200 | grep -E '(error|Error|ERROR|failed|Failed|FAILED)'"
echo ""
echo "# 6. 이미지 업데이트 관련 로그"
echo "docker logs watchtower --tail 200 | grep -E '(Pulling|pulling|Updated|updated|Found new|Stopping|Starting|Restarting)'"
echo ""
echo "# 7. 타임스탬프와 함께 확인"
echo "docker logs -t watchtower --tail 100"
echo ""
echo "# 8. Watchtower 설정 확인"
echo "docker inspect watchtower | grep -A 20 Env"
echo ""
echo "# 9. 현재 실행 중인 blacklist 컨테이너 정보"
echo "docker inspect blacklist-app | grep -E '(Image|Created|com.centurylinklabs.watchtower)'"
echo ""
echo "# 10. 레지스트리 연결 테스트"
echo "curl -I http://192.168.50.215:1234/v2/"
echo "curl -I http://registry.jclee.me/v2/"