#!/bin/bash
# 도커 볼륨 문제 해결 스크립트

echo "🔧 도커 볼륨 문제 해결 가이드"
echo "================================"
echo ""

echo "# 문제 유형별 해결 방법"
echo ""

echo "## 1. 볼륨 디렉토리가 없는 경우"
echo "sudo mkdir -p /opt/blacklist/instance"
echo "sudo mkdir -p /opt/blacklist/data"
echo "sudo mkdir -p /opt/blacklist/logs"
echo ""

echo "## 2. 권한 문제"
echo "sudo chown -R 1000:1000 /opt/blacklist/"
echo "sudo chmod -R 755 /opt/blacklist/"
echo ""

echo "## 3. 데이터베이스 파일이 없는 경우"
echo "# 컨테이너 내에서 데이터베이스 초기화"
echo "docker exec blacklist-app python setup_database.py"
echo ""

echo "## 4. 컨테이너 재시작으로 볼륨 다시 마운트"
echo "docker restart blacklist-app"
echo ""

echo "## 5. 볼륨 마운트 확인"
echo "docker exec blacklist-app df -h"
echo "docker exec blacklist-app mount | grep /app"
echo ""

echo "## 6. 데이터 백업"
echo "# 호스트에서 백업"
echo "sudo tar -czf /tmp/blacklist-backup-\$(date +%Y%m%d).tar.gz /opt/blacklist/"
echo ""

echo "## 7. 컨테이너 로그에서 볼륨 관련 에러 확인"
echo "docker logs blacklist-app | grep -E '(Permission|No such file|volume|mount)'"
echo ""

echo "## 8. 완전 재생성 (데이터 손실 주의!)"
echo "# 기존 컨테이너 제거"
echo "docker stop blacklist-app"
echo "docker rm blacklist-app"
echo ""
echo "# 디렉토리 재생성"
echo "sudo rm -rf /opt/blacklist/"
echo "sudo mkdir -p /opt/blacklist/{instance,data,logs}"
echo "sudo chown -R 1000:1000 /opt/blacklist/"
echo ""
echo "# 컨테이너 재실행"
echo "docker run -d \\"
echo "  --name blacklist-app \\"
echo "  --restart unless-stopped \\"
echo "  -p 2541:2541 \\"
echo "  -v /opt/blacklist/instance:/app/instance \\"
echo "  -v /opt/blacklist/data:/app/data \\"
echo "  -v /opt/blacklist/logs:/app/logs \\"
echo "  -e FLASK_ENV=production \\"
echo "  -e PORT=2541 \\"
echo "  -e REDIS_URL=redis://blacklist-redis:6379/0 \\"
echo "  -e REGTECH_USERNAME=nextrade \\"
echo "  -e REGTECH_PASSWORD='Sprtmxm1@3' \\"
echo "  -e SECUDIUM_USERNAME=nextrade \\"
echo "  -e SECUDIUM_PASSWORD='Sprtmxm1@3' \\"
echo "  --network blacklist_blacklist-network \\"
echo "  registry.jclee.me/blacklist:latest"