#!/bin/bash

# GitHub Secrets 설정 스크립트

echo "📋 GitHub Secrets 설정 시작..."
echo ""
echo "다음 명령어를 실행하여 GitHub Secrets를 설정하세요:"
echo ""
echo "# 1. Registry 인증 정보"
echo "gh secret set REGISTRY_USERNAME --body 'admin'"
echo "gh secret set REGISTRY_PASSWORD --body 'bingogo1'"
echo ""
echo "# 2. Charts 리포지토리 토큰 (GitHub Personal Access Token)"
echo "gh secret set CHARTS_REPO_TOKEN --body 'ghp_YOUR_PERSONAL_ACCESS_TOKEN'"
echo ""
echo "# 3. ArgoCD 토큰 (선택사항)"
echo "gh secret set ARGOCD_TOKEN --body 'YOUR_ARGOCD_TOKEN'"
echo ""
echo "# 4. 애플리케이션 시크릿"
echo "gh secret set SECRET_KEY --body '$(openssl rand -hex 32)'"
echo "gh secret set JWT_SECRET_KEY --body '$(openssl rand -hex 32)'"
echo "gh secret set REGTECH_USERNAME --body 'nextrade'"
echo "gh secret set REGTECH_PASSWORD --body 'Sprtmxm1@3'"
echo "gh secret set SECUDIUM_USERNAME --body 'nextrade'"
echo "gh secret set SECUDIUM_PASSWORD --body 'Sprtmxm1@3'"
echo ""
echo "# 5. GitHub Variables 설정"
echo "gh variable set SERVICE_URL --body 'https://blacklist.jclee.me'"
echo "gh variable set ARGOCD_URL --body 'https://argo.jclee.me'"
echo ""
echo "💡 CHARTS_REPO_TOKEN 생성 방법:"
echo "1. https://github.com/settings/tokens 접속"
echo "2. 'Generate new token (classic)' 클릭"
echo "3. 권한 선택: repo, workflow"
echo "4. 생성된 토큰을 위 명령어에 입력"