#!/bin/bash
# Watchtower 설정 수정 스크립트

echo "🔧 Watchtower 설정 수정..."
echo ""
echo "운영 서버에서 실행할 명령:"
echo ""
echo "# 1. 현재 실행 중인 컨테이너 확인"
echo "docker ps | grep blacklist"
echo ""
echo "# 2. 현재 이미지 확인"
echo "docker images | grep blacklist"
echo ""
echo "# 3. Watchtower 로그 확인"
echo "docker logs watchtower --tail 50 | grep -E '(blacklist|error|Error)'"
echo ""
echo "# 4. 올바른 이미지로 컨테이너 재생성"
echo "docker stop blacklist-app"
echo "docker rm blacklist-app"
echo ""
echo "docker run -d \\"
echo "  --name blacklist-app \\"
echo "  --restart unless-stopped \\"
echo "  --network blacklist_blacklist-network \\"
echo "  -p 2541:2541 \\"
echo "  -v /opt/blacklist/instance:/app/instance \\"
echo "  -v /opt/blacklist/data:/app/data \\"
echo "  -v /opt/blacklist/logs:/app/logs \\"
echo "  -e FLASK_ENV=production \\"
echo "  -e PORT=2541 \\"
echo "  -e REDIS_URL=redis://blacklist-redis:6379/0 \\"
echo "  -e REGTECH_USERNAME=nextrade \\"
echo "  -e REGTECH_PASSWORD='Sprtmxm1@3' \\"
echo "  -e SECUDIUM_USERNAME=nextrade \\"
echo "  -e SECUDIUM_PASSWORD='Sprtmxm1@3' \\"
echo "  --label 'com.centurylinklabs.watchtower.enable=true' \\"
echo "  192.168.50.215:1234/blacklist:latest"
echo ""
echo "# 5. Watchtower 재시작 (이미지 주소 인식하도록)"
echo "docker restart watchtower"
echo ""
echo "# 6. 수동으로 Watchtower 실행"
echo "docker run --rm \\"
echo "  -v /var/run/docker.sock:/var/run/docker.sock \\"
echo "  containrrr/watchtower \\"
echo "  --run-once \\"
echo "  blacklist-app"