#!/bin/bash
# 운영 서버 강제 업데이트 스크립트

echo "🔄 운영 서버 강제 업데이트..."
echo ""
echo "다음 명령을 운영 서버에서 실행하세요:"
echo ""
echo "# SSH 접속"
echo "ssh docker@192.168.50.215 -p 1111"
echo ""
echo "# 최신 이미지 풀"
echo "docker pull 192.168.50.215:1234/blacklist:latest"
echo ""
echo "# 기존 컨테이너 재시작"
echo "docker-compose down && docker-compose up -d"
echo ""
echo "# 또는 수동으로"
echo "docker stop blacklist-app"
echo "docker rm blacklist-app"
echo "docker run -d \\"
echo "  --name blacklist-app \\"
echo "  --restart unless-stopped \\"
echo "  --network blacklist_blacklist-network \\"
echo "  -p 2541:2541 \\"
echo "  -v /opt/blacklist/instance:/app/instance \\"
echo "  -v /opt/blacklist/data:/app/data \\"
echo "  -v /opt/blacklist/logs:/app/logs \\"
echo "  -e FLASK_ENV=production \\"
echo "  -e PORT=2541 \\"
echo "  -e REDIS_URL=redis://blacklist-redis:6379/0 \\"
echo "  -e REGTECH_USERNAME=nextrade \\"
echo "  -e REGTECH_PASSWORD='Sprtmxm1@3' \\"
echo "  -e SECUDIUM_USERNAME=nextrade \\"
echo "  -e SECUDIUM_PASSWORD='Sprtmxm1@3' \\"
echo "  192.168.50.215:1234/blacklist:latest"
echo ""
echo "# 로그 확인"
echo "docker logs -f blacklist-app"