#!/bin/bash
# 운영 서버를 단일 컨테이너로 전환하는 스크립트

echo "🔄 운영 서버 단일 컨테이너 전환 가이드"
echo "========================================"
echo ""
echo "현재 상태: blacklist-app + blacklist-redis (2개 컨테이너)"
echo "목표 상태: blacklist (1개 컨테이너, 메모리 캐시)"
echo ""
echo "운영 서버에서 다음 명령을 실행하세요:"
echo ""
echo "# 1. SSH 접속"
echo "ssh docker@192.168.50.215 -p 1111"
echo ""
echo "# 2. 현재 컨테이너 확인"
echo "docker ps | grep blacklist"
echo ""
echo "# 3. 기존 컨테이너들 정지 및 제거"
echo "docker stop blacklist-app blacklist-redis"
echo "docker rm blacklist-app blacklist-redis"
echo ""
echo "# 4. 최신 이미지 풀"
echo "docker pull registry.jclee.me/blacklist:latest"
echo ""
echo "# 5. 단일 컨테이너 실행 (메모리 캐시 모드)"
echo "docker run -d \\"
echo "  --name blacklist \\"
echo "  --restart unless-stopped \\"
echo "  -p 2541:2541 \\"
echo "  -v /opt/blacklist/instance:/app/instance \\"
echo "  -v /opt/blacklist/data:/app/data \\"
echo "  -v /opt/blacklist/logs:/app/logs \\"
echo "  -e FLASK_ENV=production \\"
echo "  -e PORT=2541 \\"
echo "  -e REGTECH_USERNAME=nextrade \\"
echo "  -e REGTECH_PASSWORD='Sprtmxm1@3' \\"
echo "  -e SECUDIUM_USERNAME=nextrade \\"
echo "  -e SECUDIUM_PASSWORD='Sprtmxm1@3' \\"
echo "  --label 'com.centurylinklabs.watchtower.enable=true' \\"
echo "  registry.jclee.me/blacklist:latest"
echo ""
echo "# 6. 헬스 체크"
echo "curl http://localhost:2541/health"
echo ""
echo "# 7. 상태 확인"
echo "docker ps"
echo "docker logs blacklist -f"
echo ""
echo "변경 사항:"
echo "  - 컨테이너 수: 2개 → 1개"
echo "  - 메모리 사용량: ~200MB → ~100MB"
echo "  - 캐시: Redis → 메모리"
echo "  - 관리: 간소화"
echo ""
echo "참고: Redis 데이터는 주로 캐시용이므로 손실되어도 문제없습니다."